import { Injectable } from '@nestjs/common';
import { CatalogItem } from './catalog.types';

@Injectable()
export class CatalogService {
    private readonly catalog: CatalogItem[] = [
        {
            id: 101,
            title: 'Neighborhood Dog Walk',
            provider: 'John Doe',
            price: 15,
            category: 'Walking',
            species: ['dog'],
            tags: ['exercise', 'social'],
            description: 'A 30-minute neighborhood walk with water breaks.',
        },
        {
            id: 102,
            title: 'Gentle Cat Grooming',
            provider: 'Jane Smith',
            price: 45,
            category: 'Grooming',
            species: ['cat'],
            tags: ['coat-care', 'low-stress'],
            description: 'Brushing, nail care, and a calm grooming session.',
        },
        {
            id: 103,
            title: 'Overnight Pet Sitting',
            provider: 'PetPal Care',
            price: 60,
            category: 'Sitting',
            species: ['cat', 'dog'],
            tags: ['overnight', 'companionship'],
            description: 'Care and companionship at home through the night.',
        },
        {
            id: 104,
            title: 'Active Dog Adventure',
            provider: 'Trail Tails',
            price: 38,
            category: 'Walking',
            species: ['dog'],
            tags: ['exercise', 'social', 'outdoors'],
            description: 'A longer outdoor outing for dogs that love to move.',
        },
        {
            id: 105,
            title: 'Puppy Social Hour',
            provider: 'Happy Paws',
            price: 28,
            category: 'Training',
            species: ['dog'],
            tags: ['social', 'training', 'exercise'],
            description:
                'Supervised play and basic social skills for young dogs.',
        },
        {
            id: 106,
            title: 'Dog Bath and Brush',
            provider: 'Clean Paws',
            price: 35,
            category: 'Grooming',
            species: ['dog'],
            tags: ['coat-care', 'hygiene'],
            description: 'A bath, dry, and thorough brushing.',
        },
        {
            id: 107,
            title: 'Senior Dog Stroll',
            provider: 'John Doe',
            price: 18,
            category: 'Walking',
            species: ['dog'],
            tags: ['gentle-exercise', 'low-stress'],
            description: 'A relaxed walk paced for older dogs.',
        },
        {
            id: 108,
            title: 'Dog Manners Coaching',
            provider: 'Happy Paws',
            price: 52,
            category: 'Training',
            species: ['dog'],
            tags: ['training', 'social'],
            description: 'One-on-one practice with everyday cues and manners.',
        },
        {
            id: 109,
            title: 'Cat Play Visit',
            provider: 'Whisker Watch',
            price: 22,
            category: 'Sitting',
            species: ['cat'],
            tags: ['play', 'companionship'],
            description: 'A home visit with play, feeding, and fresh water.',
        },
        {
            id: 110,
            title: 'Long-Hair Cat Care',
            provider: 'Jane Smith',
            price: 48,
            category: 'Grooming',
            species: ['cat'],
            tags: ['coat-care', 'hygiene', 'low-stress'],
            description: 'Extra brushing and tangle prevention for long coats.',
        },
        {
            id: 111,
            title: 'Calm Cat Sitting',
            provider: 'Whisker Watch',
            price: 32,
            category: 'Sitting',
            species: ['cat'],
            tags: ['low-stress', 'companionship'],
            description: 'Quiet home care for cats who prefer familiar spaces.',
        },
        {
            id: 112,
            title: 'Interactive Cat Play',
            provider: 'Pounce Club',
            price: 25,
            category: 'Enrichment',
            species: ['cat'],
            tags: ['play', 'exercise'],
            description: 'Guided play with toys and climbing activities.',
        },
        {
            id: 113,
            title: 'Pet Wellness Check',
            provider: 'PetPal Care',
            price: 30,
            category: 'Wellness',
            species: ['cat', 'dog'],
            tags: ['wellness', 'low-stress'],
            description:
                'A non-medical check-in on appetite, activity, and comfort.',
        },
        {
            id: 114,
            title: 'Cat Nail Care',
            provider: 'Jane Smith',
            price: 20,
            category: 'Grooming',
            species: ['cat'],
            tags: ['hygiene', 'low-stress'],
            description: 'A short, gentle nail-trimming visit.',
        },
        {
            id: 115,
            title: 'Dog Daytime Companion',
            provider: 'PetPal Care',
            price: 42,
            category: 'Sitting',
            species: ['dog'],
            tags: ['companionship', 'social', 'play'],
            description: 'Daytime company, play, and routine care.',
        },
        {
            id: 116,
            title: 'Fetch and Fitness',
            provider: 'Trail Tails',
            price: 32,
            category: 'Enrichment',
            species: ['dog'],
            tags: ['exercise', 'play', 'outdoors'],
            description: 'An energetic fetch session with rest and hydration.',
        },
        {
            id: 117,
            title: 'At-Home Pet Care Visit',
            provider: 'PetPal Care',
            price: 26,
            category: 'Sitting',
            species: ['cat', 'dog'],
            tags: ['companionship', 'low-stress'],
            description: 'Feeding, water, and company in your pet’s own home.',
        },
        {
            id: 118,
            title: 'Dog Coat Refresh',
            provider: 'Clean Paws',
            price: 24,
            category: 'Grooming',
            species: ['dog'],
            tags: ['coat-care', 'hygiene'],
            description:
                'A quick brush and tidy-up between full grooming visits.',
        },
    ];

    getCatalogItems(): CatalogItem[] {
        return this.catalog;
    }
}
